title: Ahmed T. Ali — Software Developer
baseURL: https://ahmed.sd/
copyright: Copyright © {year} Ahmed T. Ali. All rights reserved.
languageCode: en
pygmentsCodeFences: true
pygmentsUseClasses: true

outputs:
  home:
    - html
  section:
    - html
    - rss
  taxonomyTerm:
    - html
  taxonomy:
    - html

outputFormats:
  rss:
    mediaType: application/rss+xml
    baseName: rss

menu:
  main:
    - identifier: posts
      name: Blog
      url: /posts/

taxonomies:
  tag: tags

params:
  about: A personal website by Ahmed T. Ali. I write about the things I build,
    and the adventures I go through in life.
  links:
    - name: GitHub
      url: https://github.com/z0al
    - name: Twitter
      url: https://twitter.com/_z0al
    - name: Keybase
      url: https://keybase.io/z0al
    - name: Email
      url: 'mailto:ah.tajelsir@gmail.com'

disableKinds:
  - taxonomyTerm
